version: "3"

services:
  readingreview-web:
    build:
      context: .
      dockerfile: Dockerfile-web
    depends_on:
      - redis
      - rabbitmq
    environment:
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F
      PORT: ${PORT}
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
    ports:
      - ${PORT}:${PORT}

  readingreview-consumer:
    build:
      context: .
      dockerfile: Dockerfile-consumer
    depends_on:
      - redis
      - rabbitmq
      - readingreview-mock-server
    environment:
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F
      GOODREADS_URL: https://www.goodreads.com
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
      PROFILE: ${PROFILE}
      NUM_THREADS: 4

  readingreview-mock-server:
    build:
      context: .
      dockerfile: Dockerfile-mock-server
    depends_on:
      - redis
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F
    ports:
      - 8082:8082

  redis:
    image: redis:5.0.5

  rabbitmq:
    image: rabbitmq:3.6

