(ns goodstats.constants
  )

(goog-define SERVER_ADDR "http://localhost:8080")

(defonce QUOTES ["\"Be yourself; everyone else is already taken.\"― Oscar Wilde"
                 "\"Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.\" ― Albert Einstein"
                 "\"So many books, so little time.\" ― Frank Zappa"
                 "\"A room without books is like a body without a soul.\" ― Marcus Tullius Cicero"
                 "\"Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.\" ― Bernard M. Baruch"
                 "\"You know you're in love when you can't fall asleep because reality is finally better than your dreams.\" ― Dr. Seuss"
                 "\"You only live once, but if you do it right, once is enough.\" ― Mae West"
                 "\"Be the change that you wish to see in the world.\" ― Mahatma Gandhi"
                 "\"In three words I can sum up everything I've learned about life: it goes on.\" ― Robert Frost"
                 "\"If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.\" ― J.K. Rowling"
                 "\"No one can make you feel inferior without your consent.\" ― Eleanor Roosevelt, This is My Story"
                 "\"A friend is someone who knows all about you and still loves you.\" ― Elbert Hubbard"
                 "\"Always forgive your enemies; nothing annoys them so much.\" ― Oscar Wilde"
                 "\"To live is the rarest thing in the world. Most people exist, that is all.\" ― Oscar Wilde"
                 "\"Live as if you were to die tomorrow. Learn as if you were to live forever.\" ― Mahatma Gandhi"
                 "\"Without music, life would be a mistake.\" ― Friedrich Nietzsche"
                 "\"I am so clever that sometimes I don't understand a single word of what I am saying.\" ― Oscar Wilde"
                 "\"We accept the love we think we deserve.\" ― Stephen Chbosky"
                 "\"Insanity is doing the same thing, over and over again, but expecting different results.\" ― Narcotics Anonymous"
                 "\"It is our choices, Harry, that show what we truly are, far more than our abilities.\" ― J.K. Rowling"
                 "\"The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid\". ― Jane Austen"
                 "\"Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.\" ― Marilyn Monroe"
                 "\"It does not do to dwell on dreams and forget to live.\" ― J.K. Rowling"
                 "\"As he read, I fell in love the way you fall asleep: slowly, and then all at once.\" ― John Green"
                 "\"Good friends, good books, and a sleepy conscience: this is the ideal life.\" ― Mark Twain"
                 "\"We are all in the gutter, but some of us are looking at the stars.\" ― Oscar Wilde, Lady Windermere's Fan"
                 "\"The fool doth think he is wise, but the wise man knows himself to be a fool.\" ― William Shakespeare"
                 "\"Whenever you find yourself on the side of the majority, it is time to reform (or pause and reflect).\" ― Mark Twain"
                 "\"Life is what happens to us while we are making other plans.\" ― Allen Saunders"
                 "\"Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.\" ― Bill Keane"
                 "\"I have not failed. I've just found 10,000 ways that won't work.\" ― Thomas A. Edison"
                 "\"A woman is like a tea bag; you never know how strong it is until it's in hot water.\" ― Eleanor Roosevelt"
                 "\"It is not a lack of love, but a lack of friendship that makes unhappy marriages.\" ― Friedrich Nietzsche"
                 "\"The man who does not read has no advantage over the man who cannot read.\" ― Mark Twain"
                 "\"If you don't stand for something you will fall for anything.\" ― Gordon A. Eadie"
                 "\"I may not have gone where I intended to go, but I think I have ended up where I needed to be.\" ― Douglas Adams"
                 "\"I solemnly swear that I am up to no good.\" ― J.K. Rowling"
                 "\"Outside of a dog, a book is man's best friend. Inside of a dog it's too dark to read.\" ― Groucho Marx"
                 "\"I like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living.\" ― Dr. Seuss"
                 "\"Love all, trust a few, do wrong to none.\" ― William Shakespeare"
                 "\"We read to know we're not alone.\" ― William Nicholson, Shadowlands"
                 "\"You can never get a cup of tea large enough or a book long enough to suit me.\" ― C.S. Lewis"
                 "\"All you need is love. But a little chocolate now and then doesn't hurt.\" ― Charles M. Schulz"
                 "\"Today you are You, that is truer than true. There is no one alive who is Youer than You.\" ― Dr. Seuss"
                 "\"Life isn't about finding yourself. Life is about creating yourself.\" ― George Bernard Shaw"
                 "\"To the well-organized mind, death is but the next great adventure.\" ― J.K. Rowling"
                 "\"I'm not afraid of death; I just don't want to be there when it happens.\" ― Woody Allen"
                 "\"If one cannot enjoy reading a book over and over again, there is no use in reading it at all.\" ― Oscar Wilde"
                 "\"Logic will get you from A to Z; imagination will get you everywhere.\" ― Albert Einstein"
                 "\"Whenever I feel the need to exercise, I lie down until it goes away.\" ― Paul Terry"
                 "\"The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.\" ― Bob Marley"
                 "\"Folks are usually about as happy as they make their minds up to be.\" ― Abraham Lincoln"
                 "\"Do what you can, with what you have, where you are.\" ― Theodore Roosevelt"
                 "\"One good thing about music, when it hits you, you feel no pain.\" ― Bob Marley"
                 "\"There is no friend as loyal as a book.\" ― Ernest Hemingway"
                 "\"I find television very educating. Every time somebody turns on the set, I go into the other room and read a book.\" ― Groucho Marx"
                 "\"Not all of us can do great things. But we can do small things with great love.\" ― Mother Teresa"
                 "\"No Karen, you can't skip the line.\" ― Me"
                 "\"Lonzo Ball is getting MVP this year, guaranteed!\" ― Me"
                 "\"They don't want us to know the truth!\" ― Your weird uncle on Facebook"
                 "\"Man, I can't wait to be in large social gatherings in the next 12 months.\" ― Me, in January"
                 "\"It's lit!\" ― Travi$ Scott"
                 "\"YEUGH!\" ― Pusha T"
                 "\"Damn, this pangolin is looking tasty!\" ― Some guy"
                 "\"Looks at all those chickens!\" ― That girl on Vine"
                 "\"Oh my god they were room mates\" ― That guy on Vine"
                 "\"Mark Zuckerberg invest 1 million dollars in Kanye West ideas\" ― Kanye West"
                 "\"I can't wait for this two week quarantine to be over\" ― Probably you"])
